# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zooratura.com
title: Zooratura
email: zooratural@gmail.com
description: > # "Zooratura is a collection of jewelry and DIY lamp shades inspired by amazing nature illustrations of intricate and typically microscopic creatures and plants.""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: shop
    url: http://zooratura.storenvy.com
  - title: twitter
    url: https://twitter.com/zooratura
  - title: facebook
    url: https://www.facebook.com/Zooratura
